spring:
  web:
    resources:
      static-locations: file:app/src/main/resources/static/
  mail:
    host: smtp.qq.com
    port: 465
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: truemis
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.connectiontimeout: 8000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000
