server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:file:./data/devops;MODE=MySQL;AUTO_SERVER=TRUE;
    driver-class-name: org.h2.Driver
    username: sa
    password:
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: "SELECT 1"
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      keep-alive: true
      pool-prepared-statements: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.css,*.png,*.jpg,*.gif,*.ico,/druid/*"
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/schema.sql
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
  global-config:
    banner: false
    enable-sql-runner: true
    db-config:
      id-type: assign_id
      table-underline: true